logging:
  level:
    org.springframework.web: DEBUG

spring:
  application:
    name: DCS
  datasource:
    ## default connection pool
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    ## PostgreSQL
    url: jdbc:postgresql://127.0.0.1:5432/dashboards #jdbc:postgresql://10.9.8.202:5432/dashboards
    username: eve
    password: changeme
  jpa:
    #this one is for production envs:
    generate-ddl: true
#    hibernate:
#      ddl-auto: create

keycloak-admin:
  server-url: http://10.5.7.11:8080/auth #http://10.9.8.228:8080/auth
  realm: master
  username: changeme
  password: changeme
  client-id: admin-cli
  users-realm: changeme

keycloak-user: changeme
keycloak-password: changeme
nginx-file: changeme

#enable kibana interaction
kibana:
  client-id: changeme
  client-secret: changeme
  token-uri: http://10.5.7.11:8080/auth/realms/5geve/protocol/openid-connect/token
  enabled: true
  dashboard-owner-enabled: true
  oauth-enabled: true
  baseUrl: http://10.9.8.202:5601
  dashboardUrl: https://portal.5g-eve.eu/portal/metrics/dashboard

keycloak.realm: changeme
keycloak.auth-server-url: http://10.5.7.11:8080/auth #http://10.9.8.228:8080/auth
keycloak.ssl-required: external
keycloak.resource: changeme
keycloak.credentials.secret: changeme
keycloak.use-resource-role-mappings: true
keycloak.bearer-only: true

elasticsearch.ip_port: http://10.9.8.151:9200/
