spring:
  application:
    name: DCS
  datasource:
    ## default connection pool
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    ## PostgreSQL
    #url: jdbc:postgresql://10.9.8.202:5432/dashboards
    url: jdbc:postgresql://127.0.0.1:5432/dashboards
    username: eve
    password: changeme
  jpa:
    #this one is for production envs:
    generate-ddl: true
    #hibernate:
      #ddl-auto: create


#enable kibana interaction
kibana:
  enabled: true
  dashboard-owner-enabled: false
  oauth-enabled: false
  baseUrl: http://127.0.0.1:5601